### ISSUE TITLE
Invalid values in cpuPercent

### ISSUE THREAD

**Issue by mangulonr** [newrelic/nri-docker#69] opened 2021-06-30 14:13 UTC
cpuPercent in ContainerSample is reporting values of more than 32 Billions. 

For more information check this [Customer Feedback ticket](https://newrelic.atlassian.net/browse/CF-6591?jql=project%20IN%20(24930)%20%20and%20assignee%20in%20(557058%3A4f053f27-7b67-47ec-ac40-b16e9ea66cdb%2C%2060644959b30f0d00702e8358)%20and%20status%20!%3D%20Done)

**Comment by roobre** [comment] 2021-07-06 12:08
Closing as this seemed to be caused by a wrong value reported by docker/cgroups themselves.

**Closed by roobre** 2021-07-06 12:08 UTC
Labels: priority/pending, triage/accepted
